config/routes.rb
Rails.application.routes.draw do
  mount Payola::Engine => '/payola', as: :payola
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'

  mount PgHero::Engine, at: "pghero"

  get '/home', to: 'dashboard#home'

  namespace :api do
    post '/check', to: 'status#check'

    get '/', to: 'docs#index'
    get '/search', to: 'search#index'
    get '/bower-search', to: 'bower_search#index'
    get '/searchcode', to: 'projects#searchcode'

    get '/platforms', to: 'platforms#index'

    get '/subscriptions', to: 'subscriptions#index'
    get '/subscriptions/:platform/:name', to: 'subscriptions#show'
    post '/subscriptions/:platform/:name', to: 'subscriptions#create'
    put '/subscriptions/:platform/:name', to: 'subscriptions#update'
    delete '/subscriptions/:platform/:name', to: 'subscriptions#destroy'

    # legacy due to typo
    get '/subscription/:platform/:name', to: 'subscriptions#show'
    post '/subscription/:platform/:name', to: 'subscriptions#create'
    put '/subscription/:platform/:name', to: 'subscriptions#update'
    delete '/subscription/:platform/:name', to: 'subscriptions#destroy'

    scope constraints: {host_type: /(github|gitlab|bitbucket)/i}, defaults: { host_type: 'github' } do
      get '/:host_type/issues/help-wanted', to: 'issues#help_wanted'
      get '/:host_type/issues/first-pull-request', to: 'issues#first_pull_request'

      get '/:host_type/search', to: 'repositories#search'

      get '/:host_type/:login/repositories', to: 'repository_users#repositories'
      get '/:host_type/:login/projects', to: 'repository_users#projects'

      get '/:host_type/:owner/:name/dependencies', to: 'repositories#dependencies', constraints: { :name => /[^\/]+/ }
      get '/:host_type/:owner/:name/projects', to: 'repositories#projects', constraints: { :name => /[^\/]+/ }
      get '/:host_type/:owner/:name', to: 'repositories#show', constraints: { :name => /[^\/]+/ }

      get '/:host_type/:login', to: 'repository_users#show'
    end

    get '/:platform/:name/:version/tree', to: 'tree#show', constraints: { :platform => /[\w\-]+/, :name => /[\w\-\%]+/, :version => /[\w\.\-]+/ }, as: :version_tree
    get '/:platform/:name/:version/dependencies', to: 'projects#dependencies', constraints: { :platform => /[\w\-]+/, :name => /[\w\-\%]+/, :version => /[\w\.\-]+/ }
    get '/:platform/:name/dependent_repositories', to: 'projects#dependent_repositories', constraints: { :platform => /[\w\-]+/, :name => /[\w\.\-\%]+/ }
    get '/:platform/:name/dependents', to: 'projects#dependents', constraints: { :platform => /[\w\-]+/, :name => /[\w\.\-\%]+/ }
    get '/:platform/:name/tree', to: 'tree#show', constraints: { :platform => /[\w\-]+/, :name => /[\w\.\-\%]+/ }, as: :tree
    get '/:platform/:name', to: 'projects#show', constraints: { :platform => /[\w\-]+/, :name => /[\w\.\-\%]+/ }
  end

  namespace :admin do
    resources :projects do
      collection do
        get 'deprecated'
        get 'unmaintained'
      end
    end
    resources :project_suggestions
    resources :repositories do
      member do
        put 'deprecate'
        put 'unmaintain'
      end
      collection do
        get 'deprecated'
        get 'unmaintained'
      end
    end
    get '/stats', to: 'stats#index', as: :stats
    get '/stats/repositories', to: 'stats#repositories', as: :repositories_stats
    get '/graphs', to: 'stats#graphs', as: :graphs
    get '/', to: 'stats#overview', as: :overview
  end

  get '/trending', to: 'projects#trending', as: :trending_projects
  get '/explore', to: 'explore#index'
  get '/collections', to: 'collections#index', as: :collections
  get '/explore/:language-:keyword-libraries', to: 'collections#show', as: :collection

  get '/pricing', to: 'account_subscriptions#plans', as: :pricing
  resources :account_subscriptions

  get '/recommendations', to: 'recommendations#index', as: :recommendations

  get '/repositories', to: 'dashboard#index', as: :repositories
  get '/dashboard', to: redirect("/repositories")
  get '/muted', to: 'dashboard#muted', as: :muted
  post '/repositories/sync', to: 'dashboard#sync', as: :sync
  post '/watch/:repository_id', to: 'dashboard#watch', as: :watch
  post '/unwatch/:repository_id', to: 'dashboard#unwatch', as: :unwatch

  resource :account do
    member do
      get 'delete'
      put 'disable_emails'
    end
  end

  root to: 'projects#index'

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'

  resources :licenses, constraints: { :id => /.*/ }, :defaults => { :format => 'html' }
  resources :languages
  resources :keywords, constraints: { :id => /.*/ }, :defaults => { :format => 'html' }
  resources :subscriptions
  resources :repository_subscriptions
  get '/subscribe/:project_id', to: 'subscriptions#subscribe', as: :subscribe

  get '/stats', to: redirect('/admin/stats')

  #explore
  get '/explore/unlicensed-libraries', to: 'projects#unlicensed', as: :unlicensed
  get '/explore/unmaintained-libraries', to: 'projects#unmaintained', as: :unmaintained
  get '/explore/deprecated-libraries', to: 'projects#deprecated', as: :deprecated
  get '/explore/removed-libraries', to: 'projects#removed', as: :removed
  get '/explore/help-wanted', to: 'issues#help_wanted', as: :help_wanted
  get '/explore/first-pull-request', to: 'issues#first_pull_request', as: :first_pull_request
  get '/explore/issues', to: 'issues#index', as: :all_issues
  get '/unlicensed-libraries', to: redirect("/explore/unlicensed-libraries")
  get 'unmaintained-libraries', to: redirect("/explore/unmaintained-libraries")
  get 'deprecated-libraries', to: redirect("/explore/deprecated-libraries")
  get 'removed-libraries', to: redirect("/explore/removed-libraries")
  get '/help-wanted', to: redirect("/explore/help-wanted")
  get '/first-pull-request', to: redirect("/explore/first-pull-request")
  

  get '/platforms', to: 'platforms#index', as: :platforms

  scope constraints: {host_type: /(github|gitlab|bitbucket)/i}, defaults: { host_type: 'github' } do
    get '/:host_type/issues', to: 'issues#index', as: :issues
    get '/:host_type/issues/your-dependencies', to: 'issues#your_dependencies', as: :your_dependencies_issues

    post '/hooks/:host_type', to: 'hooks#github'

    get '/:host_type/languages', to: 'repositories#languages', as: :github_languages
    get '/:host_type/search', to: 'repositories#search', as: :github_search
    get '/:host_type/trending', to: 'repositories#hacker_news', as: :trending
    get '/:host_type/new', to: 'repositories#new', as: :new_repos
    get '/:host_type/organisations', to: 'repository_organisations#index', as: :repository_organisations
    get '/:host_type/timeline', to: 'repositories#timeline', as: :github_timeline
    get '/:host_type/:login/issues', to: 'repository_users#issues'
    get '/:host_type/:login/dependencies', to: 'repository_users#dependencies', as: :user_dependencies
    get '/:host_type/:login/dependency-issues', to: 'repository_users#dependency_issues'
    get '/:host_type/:login/repositories', to: 'repository_users#repositories', as: :user_repositories
    get '/:host_type/:login/contributions', to: 'repository_users#contributions', as: :user_contributions
    get '/:host_type/:login/projects', to: 'repository_users#projects', as: :user_projects
    get '/:host_type/:login/contributors', to: 'repository_users#contributors', as: :user_contributors
    get '/:host_type/:login', to: 'repository_users#show', as: :user

    get '/:host_type/:owner/:name', to: 'repositories#show', as: :repository, :defaults => { :format => 'html' }, constraints: { :name => /[\w\.\-\%]+/ }
    get '/:host_type/:owner/:name/contributors', to: 'repositories#contributors', as: :repository_contributors, format: false, constraints: { :name => /[^\/]+/ }
    post '/:host_type/:owner/:name/sync', to: 'repositories#sync', as: :sync_repository, format: false, constraints: { :name => /[^\/]+/ }
    get '/:host_type/:owner/:name/sourcerank', to: 'repositories#sourcerank', as: :repository_sourcerank, format: false, constraints: { :name => /[^\/]+/ }
    get '/:host_type/:owner/:name/forks', to: 'repositories#forks', as: :repository_forks, format: false, constraints: { :name => /[^\/]+/ }
    get '/:host_type/:owner/:name/tags', to: 'repositories#tags', as: :repository_tags, format: false, constraints: { :name => /[^\/]+/ }
    get '/:host_type/:owner/:name/dependency-issues', to: 'repositories#dependency_issues', format: false, constraints: { :name => /[^\/]+/ }
    get '/:host_type/:owner/:name/dependencies', to: 'repositories#dependencies', format: false, constraints: { :name => /[^\/]+/ }, as: :repository_dependencies
    get '/:host_type/:owner/:name/tree', to: 'repository_tree#show', as: :repository_tree, format: false, constraints: { :name => /[^\/]+/ }

    get '/:host_type/:owner/:name/web_hooks', to: 'web_hooks#index', as: :repository_web_hooks, format: false, constraints: { :name => /[^\/]+/ }
    get '/:host_type/:owner/:name/web_hooks/new', to: 'web_hooks#new', as: :new_repository_web_hook, format: false, constraints: { :name => /[^\/]+/ }
    delete '/:host_type/:owner/:name/web_hooks/:id', to: 'web_hooks#destroy', as: :repository_web_hook, format: false, constraints: { :name => /[^\/]+/ }
    patch '/:host_type/:owner/:name/web_hooks/:id', to: 'web_hooks#update', format: false, constraints: { :name => /[^\/]+/ }
    get '/:host_type/:owner/:name/web_hooks/:id/edit', to: 'web_hooks#edit', as: :edit_repository_web_hook, format: false, constraints: { :name => /[^\/]+/ }
    post '/:host_type/:owner/:name/web_hooks/:id/test', to: 'web_hooks#test', as: :test_repository_web_hook, format: false, constraints: { :name => /[^\/]+/ }

app/models/repositories/nuget.rb
module Repositories
  class NuGet < Base
    HAS_VERSIONS = true
    HAS_DEPENDENCIES = true
    LIBRARIAN_SUPPORT = true
    URL = 'https://www.nuget.org'
    COLOR = '#178600'

    def self.load_names(limit = nil)
      endpoints = name_endpoints
      segment_count = limit || endpoints.length - 1

      endpoints.reverse[0..segment_count].each do |endpoint|
        package_ids = get_names(endpoint)
        package_ids.each { |id| REDIS.sadd 'nuget-names', id }
      end
      puts "Loaded all the names"
    end

    def self.recent_names
      name_endpoints.reverse[0..2].map{|url| get_names(url) }.flatten.uniq
    end

    def self.name_endpoints
      get('https://api.nuget.org/v3/catalog0/index.json')['items'].map{|i| i['@id']}
    end

    def self.get_names(endpoint)
      get(endpoint)['items'].map{|i| i["nuget:id"]}
    end

    def self.project_names
      REDIS.smembers 'nuget-names'
    end

    def self.project(name)
      h = {
        name: name
      }
      h[:versions] = versions(h)
      h
    end

    def self.mapping(project)
      latest_version = get_json("https://api.nuget.org/v3/registration1/#{project[:name].downcase}/index.json")
      item = latest_version['items'].last['items'].last['catalogEntry']

      {
        name: project[:name],
        description: description(item),
        homepage: item['projectUrl'],
        keywords_array: Array(item['tags']),
        repository_url: repo_fallback('', item['projectUrl'])
      }
    end

    def self.description(item)
      item['description'].blank? ? item['summary'] : item['description']
    end

    def self.versions(project)
      latest_version = get_json("https://api.nuget.org/v3/registration1/#{project[:name].downcase}/index.json")
      latest_version['items'].first['items'].map do |item|
        {
          number: item['catalogEntry']['version'],
          published_at: item['catalogEntry']['published']
        }
      end
    end

    def self.dependencies(name, version)
      versions = get_json("https://api.nuget.org/v3/registration1/#{name.downcase}/index.json")
      all_versions = versions['items'].first['items']
      current_version = all_versions.find{|v| v['catalogEntry']['version'] == version }
      dep_groups = current_version['catalogEntry']['dependencyGroups'] || []

      deps = dep_groups.map do |dep_group|
        dep_group["dependencies"].map do |dependency|
          {
            name: dependency['id'],
            requirements: parse_requirements(dependency['range'])
          }
        end
      end.flatten.compact

      deps.map do |dep|
        {
          project_name: dep[:name],
          requirements: dep[:requirements],
          kind: 'normal',
          optional: false,
          platform: self.name.demodulize
        }
      end
    end

    def self.parse_requirements(range)
      parts = range[1..-2].split(',')
      requirements = []
      low_bound = range[0]
      high_bound = range[-1]
      low_number = parts[0].strip
      high_number = parts[1].try(:strip)

      # lowest
      low_sign = low_bound == '[' ? '>=' : '>'
      high_sign = high_bound == ']' ? '<=' : '<'

      # highest
      if high_number
        if high_number != low_number
          requirements << "#{low_sign} #{low_number}" if low_number.present?
          requirements << "#{high_sign} #{high_number}" if high_number.present?
        elsif high_number == low_number
          requirements << "= #{high_number}"
        end
      else
        requirements << "#{low_sign} #{low_number}" if low_number.present?
      end
      requirements << '>= 0' if requirements.empty?
      requirements.join(' ')
    end
  end
end

app/models/repositories/swift.rb
module Repositories
  class Swift < Base
    HAS_VERSIONS = false
    HAS_DEPENDENCIES = false
    LIBRARIAN_SUPPORT = false
    URL = 'https://developer.apple.com/swift/'
    COLOR = '#ffac45'

    def self.project_names
      @project_names ||= `rm -rf swift-package-crawler-data;git clone https://github.com/czechboy0/swift-package-crawler-data.git --depth 1; ls swift-package-crawler-data/PackageJSONFiles`.split("\n")
    end

    def self.project(name)
      name_with_owner = name.gsub("-Package.json", "").split('_').join('/')
      {
        name: "github.com/#{name_with_owner}",
        repository_url: "https://github.com/#{name_with_owner}"
      }
    end

    def self.mapping(project)
      {
        :name => project[:name],
        :repository_url => project[:repository_url]
      }
    end
  end
end

app/controllers/admin/repositories_controller.rb
class Admin::RepositoriesController < Admin::ApplicationController
  def show
    @repository = Repository.find(params[:id])
  end

  def update
    @repository = Repository.find(params[:id])
    if @repository.update_attributes(repository_params)
      @repository.update_all_info_async
      redirect_to repository_path(@repository.to_param)
    else
      redirect_to admin_repository_path(@repository.id)
    end
  end

  def deprecate
    change(:deprecate!)
  end

  def unmaintain
    change(:unmaintain!)
  end

  def index
    if params[:language].present?
      @language = Linguist::Language[params[:language]].try(:to_s)
      raise ActiveRecord::RecordNotFound if @language.nil?
      scope = Repository.language(@language)
    else
      scope = Repository
    end

    @languages = Repository.maintained.without_license.with_projects.group('repositories.language').count.sort_by(&:last).reverse.first(20)
    @repositories = scope.maintained.without_license.with_projects.order("COUNT(projects.id) DESC").group("repositories.id").paginate(page: params[:page])
  end

  def deprecated
    search('deprecated')
  end

  def unmaintained
    search('unmaintained')
  end

  private

  def repository_params
    params.require(:repository).permit(:license, :status)
  end

  def search(query)
    @search = Repository.search(query, must_not: [
      terms: { "status" => ["Unmaintained","Active","Deprecated"] }
    ], sort: 'stargazers_count').paginate(page: params[:page])
    @repositories = @search.records
  end

  def change(method)
    @repository = Repository.find(params[:id])
    @repository.send(method)
    @repository.update_all_info_async
    redirect_to repository_path(@repository.to_param)
  end
end

app/controllers/api/repositories_controller.rb
class Api::RepositoriesController < Api::ApplicationController
  before_action :find_repo, except: :search

  def show
    render json: @repository
  end

  def projects
    paginate json: @repository.projects.order(custom_order).includes(:versions, :repository)
  end

  def dependencies
    repo_json = RepositorySerializer.new(@repository).as_json
    repo_json[:dependencies] = map_dependencies(@repository.repository_dependencies || [])

    render json: repo_json
  end

  def search
    @search = paginate(search_repos(params[:q]))
    @repositories = @search.records

    render json: @repositories
  end

  private

  def find_repo
    full_name = [params[:owner], params[:name]].join('/')
    @repository = Repository.host(current_host).open_source.where('lower(full_name) = ?', full_name.downcase).first

    raise ActiveRecord::RecordNotFound if @repository.nil?
  end

  def allowed_sorts
    ['rank', 'stargazers_count', 'contributions_count', 'created_at', 'pushed_at', 'subscribers_count', 'open_issues_count', 'forks_count', 'size']
  end
end

app/views/repositories/_search_form.html.erb
<%= form_tag repo_search_path(host_type: current_host), method: :get, class: 'navbar-form search_form', enforce_utf8: false do |f| %>
  <div class="input-group input-group">

    <div class="input-group-btn">
     <a type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Search <span class="caret"></span></a>
     <ul class="dropdown-menu">
       <li>
         <%= link_to search_path(q: params[:q], sort: params[:sort]) do %>
           <span class='fa-blank'></span>
           Libraries
         <% end %>
       </li>
       <li>
         <%= link_to repo_search_path(q: params[:q], sort: params[:sort]) do %>
           <%= fa_icon 'check' %>
           Repositories
         <% end %>
       </li>
     </ul>
   </div>

    <%= text_field_tag 'q', "#{@query || '' }", placeholder: 'Search Repositories', class: 'form-control', size: 40 %>
    <% [:license, :language, :keywords, :sort].each do |field| %>
      <%= hidden_field_tag field, params[field] if params[field].present? %>
    <% end %>
    <span class="input-group-btn">
      <button class="btn btn-primary" type="submit">
        <%= fa_icon 'search' %>
      </button>
    </span>
  </div>
<% end %>

app/views/repositories/_stats.html.erb
<table class='table table-striped'>
  <% if repo.rank %>
  <tr>
    <td>
      Sourcerank
    </td>
    <td>
      <strong><%= link_to repo.rank, repository_sourcerank_path(repo.to_param) %></strong>
    </td>
  </tr>
  <% end %>
  <% if repo.size %>
  <tr>
    <td>
      Size
    </td>
    <td>
      <strong><%= number_to_human_size repo.size*1000 %></strong>
    </td>
  </tr>
  <% end %>
  <% if repo.stargazers_count %>
  <tr>
    <td>
      Stars
    </td>
    <td>
      <strong><%= link_to_unless repo.stargazers_url.nil?, number_with_delimiter(repo.stargazers_count || 0), repo.stargazers_url %></strong>
    </td>
  </tr>
  <% end %>
  <tr>
    <td>
      Forks
    </td>
    <td>
      <strong><%= link_to_unless repo.forks_url.nil?, number_with_delimiter(repo.forks_count || 0), repo.forks_url %></strong>
    </td>
  </tr>
  <% if repo.subscribers_count.present? %>
  <tr>
    <td>
      Watchers
    </td>
    <td>
      <strong><%= link_to_unless repo.watchers_url.nil?, number_with_delimiter(repo.subscribers_count), repo.watchers_url %></strong>
    </td>
  </tr>
  <% end %>
  <% if repo.open_issues_count %>
  <tr>
    <td>
      Open issues
    </td>
    <td>
      <strong><%= repo.has_issues? ? link_to(number_with_delimiter(repo.open_issues_count || 0), repo.issues_url) : 'disabled'  %></strong>
    </td>
  </tr>
  <% end %>
  <tr>
    <td>
      Dependencies
    </td>
    <td>
      <strong><%= number_with_delimiter repo.repository_dependencies.count %></strong>
    </td>
  </tr>
  <% if repo.contributions_count > 0 %>
  <tr>
    <td>
      Contributors
    </td>
    <td>
      <strong><%= link_to number_with_delimiter(repo.contributions_count), repository_contributors_path(@repository.to_param)  %></strong>
    </td>
  </tr>
  <% end %>
  <tr>
    <td>
      Tags
    </td>
    <td>
      <strong><%= link_to number_with_delimiter(repo.tags.count), repository_tags_path(@repository.to_param)  %></strong>
    </td>
  </tr>
  <tr>
    <td>
      Created
    </td>
    <td>
      <strong><%= timeago_tag repo.created_at %></strong>
    </td>
  </tr>
  <tr>
    <td>
      Last updated
    </td>
    <td>
      <strong><%= timeago_tag repo.updated_at %></strong>
    </td>
  </tr>
  <% if repo.host_type == 'GitHub' %>
  <tr>
    <td>
      Last pushed
    </td>
    <td>
      <strong><%= repo.pushed_at.present? ? timeago_tag(repo.pushed_at) : 'Never'  %></strong>
    </td>
  </tr>
  <% end %>
</table>

app/views/repositories/show.html.erb
<% title "#{@repository.full_name} - Libraries.io" %>
<% description @repository.description_with_language %>
<%= content_for :meta, render_meta(@repository) %>
<% repo = @repository %>

<% if !repo.private? && repo.is_removed? %>
<div class="alert alert-danger" role="alert">
  <%= fa_icon 'exclamation-triangle' %>
  This repository has been removed and cannot be used anymore.
</div>
<% elsif !repo.private? && repo.is_deprecated? %>
<div class="alert alert-danger" role="alert">
  <%= fa_icon 'exclamation-triangle' %>
  This repository has been marked as deprecated and is not recommended for use anymore.
</div>
<% elsif !repo.private? && repo.is_unmaintained? %>
<div class="alert alert-danger" role="alert">
  <%= fa_icon 'exclamation-triangle' %>
  This repository has been marked as unmaintained and is no longer being updated.
</div>
<% end %>

<div class="row">
  <div class='col-md-8'>
    <h1>
      <% if repo.owner.present? %>
        <%= link_to image_tag(repo.avatar_url(100), width: 50, height: 50, alt: repo), user_path(host_type: repo.host_type.downcase, login: repo.owner_name) %>
      <% else %>
        <%= image_tag(repo.avatar_url(100), width: 50, height: 50, alt: repo) %>
      <% end %>
      <%= repo %>
      <%= link_to fa_icon(repo.host_type.downcase), repo.url, class: 'tip', title: "View #{repo} on #{repo.formatted_host}" %>
      <%= fa_icon("lock", title: 'This repo is private', class: 'tip') if repo.private? %>
      <% if repo.fork? %>
        <% if repo.source.present? || repo.source_name.present? %>
          <%= link_to fa_icon('code-fork'), source_path(repo), class: 'tip', title: "Forked from #{repo.source_name}" %>
        <% else %>
          <%= fa_icon("code-fork", title: 'This repo is a fork', class: 'tip') %>
        <% end %>
      <% end %>
    </h1>
    <% if repo.fork? %>
      <small>
        Forked
        <% if repo.source.present? || repo.source_name.present? %>
          from
          <%= link_to repo.source_name, source_path(repo) %>
        <% end %>
      </small>
    <% end %>
  </div>
  <div class="col-md-4">

    <% if current_user && current_user.can_monitor?(repo) %>
      <br>
        <br>
      <% if sub = current_user.subscribed_to_repo?(repo) %>
        <div class="btn-group pull-right">
          <%= link_to unwatch_path(repo.id), method: :post, class: 'tip btn btn-success', title: 'Stop watching' do %>
            <%= fa_icon('check') %>
            Monitoring
          <% end %>
          <%= link_to fa_icon('cog'), edit_repository_subscription_path(sub), class: 'btn btn-success' %>
        </div>
      <% else %>
        <%= button_to watch_path(repo.id), method: :post, class: 'btn btn-primary btn-default  pull-right tip', title: 'Automatically watch every dependency of this project' do %>
          <%= fa_icon('eye') %>
          Monitor dependencies
        <% end %>
      <% end %>
      <%= link_to repository_web_hooks_path(repo.to_param), class: 'btn btn-info pull-right', id: 'webhooks' do %>
        <%= fa_icon 'plug' %>
        Web Hooks
      <% end %>
    <% end %>
    <% if logged_in? && current_user.admin? %>
      <%= link_to 'Admin', admin_repository_path(repo.id), class: 'btn btn-primary pull-right', rel: 'nofollow' %>
    <% end %>
  </div>
</div>
<hr>
<div class='row'>
  <% cache([@repository, 'show', 'v2'], :expires_in => 1.day) do %>
    <div class='col-md-8'>
      <p>
        <%= emojify repo.description %>
      </p>
      <% if repo.homepage.present? %>
        <p>
          <%= link_to repo.homepage, sanitize_url(repo.homepage), :rel => 'nofollow' %>
        </p>
      <% end %>
      <% if repo.host_type.present? %>
        <p>
          Host: <%= link_to format_host(repo.host_type), hosts_path(host_type: repo.host_type.downcase) %>
        </p>
      <% end %>
      <% if repo.license.present? %>
        <p>
          License: <%= link_to format_license(repo.license), license_path(repo.license) %>
        </p>
      <% end %>
      <% if repo.language.present? %>
      <p>
        Language: <%= link_to repo.language, language_path(repo.language) %>
      </p>
      <% end %>
      <% if repo.keywords.any? %>
      <p>
        Keywords: <%= linked_repo_keywords repo.keywords %>
      </p>
      <% end %>
      <% if repo.mirror_url.present? %>
      <p>
        Mirror of <%= repo.mirror_url %>
      </p>
      <% end %>
      <% if repo.readme.present? %>
        <hr>
        <%= render 'adsense/banner' %>
        <%== repo.readme %>
      <% end %>

      <div id='repository_dependencies' style='display:none;' data-url="<%= repository_dependencies_path(repo.to_param) %>"></div>
    </div>
  <% end %>

  <div class='col-md-4'>
    <% cache([@repository, 'sidebar', 'v1'], :expires_in => 1.day) do %>
      <%= render 'adsense/sidebar' %>
      <h4>Project Statistics</h4>
      <%= render 'repositories/stats', repo: repo %>

      <% if @contributors.length > 0 %>
        <h4>Top Contributors <small><%= link_to 'See all', repository_contributors_path(@repository.to_param) %></small></h4>
        <%= render @contributors %>
      <% end %>

      <% if @projects.length > 0 %>
        <div class="row"></div>
        <hr>
        <h4>Projects Referencing this Repo</h4>
        <%= render @projects, cache: true %>
      <% end %>

      <%= render 'tags', repo: repo %>

      <% if @forks.length > 0 %>
        <div class="row"></div>
        <hr>
        <h4>
          Interesting Forks
          <small><%= link_to 'See all', repository_forks_path(@repository.to_param) %></small>
        </h4>
        <%= render @forks, cache: true %>
      <% end %>
    <% end %>

    <div class="row"></div>
    <br>
    <p>
      <%= fa_icon 'question-circle' %>
      Something wrong with this page?
      <%= link_to 'Make a suggestion', 'https://github.com/librariesio/libraries.io/issues/new' %>
    </p>
    <% if repo.last_synced_at.present? %>
      <p>
        <small class='text-muted'>Last synced: <%= repo.last_synced_at %></small>
      </p>
    <% end %>
    <% unless repo.recently_synced? %>
      <% if logged_in? %>
        <p>
          <%= link_to sync_repository_path(repo.to_param), class: 'btn btn-primary btn-xs', method: :post do %>
            <%= fa_icon 'refresh' %>
            Resync Repository
          <% end %>
        </p>
      <% else %>
        <p>
          <small class='text-muted'>
            <%= link_to 'Login', login_path %> to resync this repository
          </small>
        </p>
      <% end %>
    <% end %>
  </div>
</div>