config/routes.rb
Rails.application.routes.draw do
  mount Payola::Engine => '/payola', as: :payola
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'

  mount PgHero::Engine, at: "pghero"

  get '/home', to: 'dashboard#home'

  namespace :api do
    post '/check', to: 'status#check'

    get '/', to: 'docs#index'
    get '/search', to: 'search#index'
    get '/bower-search', to: 'bower_search#index'
    get '/searchcode', to: 'projects#searchcode'

    get '/platforms', to: 'platforms#index'

    get '/subscriptions', to: 'subscriptions#index'
    get '/subscriptions/:platform/:name', to: 'subscriptions#show'
    post '/subscriptions/:platform/:name', to: 'subscriptions#create'
    put '/subscriptions/:platform/:name', to: 'subscriptions#update'
    delete '/subscriptions/:platform/:name', to: 'subscriptions#destroy'

    # legacy due to typo
    get '/subscription/:platform/:name', to: 'subscriptions#show'
    post '/subscription/:platform/:name', to: 'subscriptions#create'
    put '/subscription/:platform/:name', to: 'subscriptions#update'
    delete '/subscription/:platform/:name', to: 'subscriptions#destroy'

    scope constraints: {host_type: /(github|gitlab|bitbucket)/i}, defaults: { host_type: 'github' } do
      get '/:host_type/issues/help-wanted', to: 'issues#help_wanted'
      get '/:host_type/issues/first-pull-request', to: 'issues#first_pull_request'

      get '/:host_type/search', to: 'repositories#search'

      get '/:host_type/:login/repositories', to: 'repository_users#repositories'
      get '/:host_type/:login/projects', to: 'repository_users#projects'

      get '/:host_type/:owner/:name/dependencies', to: 'repositories#dependencies', constraints: { :name => /[^\/]+/ }
      get '/:host_type/:owner/:name/projects', to: 'repositories#projects', constraints: { :name => /[^\/]+/ }
      get '/:host_type/:owner/:name', to: 'repositories#show', constraints: { :name => /[^\/]+/ }

      get '/:host_type/:login', to: 'repository_users#show'
    end

    get '/:platform/:name/:version/tree', to: 'tree#show', constraints: { :platform => /[\w\-]+/, :name => /[\w\-\%]+/, :version => /[\w\.\-]+/ }, as: :version_tree
    get '/:platform/:name/:version/dependencies', to: 'projects#dependencies', constraints: { :platform => /[\w\-]+/, :name => /[\w\-\%]+/, :version => /[\w\.\-]+/ }
    get '/:platform/:name/dependent_repositories', to: 'projects#dependent_repositories', constraints: { :platform => /[\w\-]+/, :name => /[\w\.\-\%]+/ }
    get '/:platform/:name/dependents', to: 'projects#dependents', constraints: { :platform => /[\w\-]+/, :name => /[\w\.\-\%]+/ }
    get '/:platform/:name/tree', to: 'tree#show', constraints: { :platform => /[\w\-]+/, :name => /[\w\.\-\%]+/ }, as: :tree
    get '/:platform/:name', to: 'projects#show', constraints: { :platform => /[\w\-]+/, :name => /[\w\.\-\%]+/ }
  end

  namespace :admin do
    resources :projects do
      collection do
        get 'deprecated'
        get 'unmaintained'
      end
    end
    resources :project_suggestions
    resources :repositories do
      member do
        put 'deprecate'
        put 'unmaintain'
      end
      collection do
        get 'deprecated'
        get 'unmaintained'
      end
    end
    get '/stats', to: 'stats#index', as: :stats
    get '/stats/repositories', to: 'stats#repositories', as: :repositories_stats
    get '/graphs', to: 'stats#graphs', as: :graphs
    get '/', to: 'stats#overview', as: :overview
  end

  get '/trending', to: 'projects#trending', as: :trending_projects
  get '/explore', to: 'explore#index'
  get '/collections', to: 'collections#index', as: :collections
  get '/explore/:language-:keyword-libraries', to: 'collections#show', as: :collection

  get '/pricing', to: 'account_subscriptions#plans', as: :pricing
  resources :account_subscriptions

  get '/recommendations', to: 'recommendations#index', as: :recommendations

  get '/repositories', to: 'dashboard#index', as: :repositories
  get '/dashboard', to: redirect("/repositories")
  get '/muted', to: 'dashboard#muted', as: :muted
  post '/repositories/sync', to: 'dashboard#sync', as: :sync
  post '/watch/:repository_id', to: 'dashboard#watch', as: :watch
  post '/unwatch/:repository_id', to: 'dashboard#unwatch', as: :unwatch

  resource :account do
    member do
      get 'delete'
      put 'disable_emails'
    end
  end

  root to: 'projects#index'

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'

  resources :licenses, constraints: { :id => /.*/ }, :defaults => { :format => 'html' }
  resources :languages
  resources :keywords, constraints: { :id => /.*/ }, :defaults => { :format => 'html' }
  resources :subscriptions
  resources :repository_subscriptions
  get '/subscribe/:project_id', to: 'subscriptions#subscribe', as: :subscribe

  get '/stats', to: redirect('/admin/stats')

  #explore
  get '/explore/unlicensed-libraries', to: 'projects#unlicensed', as: :unlicensed
  get '/explore/unmaintained-libraries', to: 'projects#unmaintained', as: :unmaintained
  get '/explore/deprecated-libraries', to: 'projects#deprecated', as: :deprecated
  get '/explore/removed-libraries', to: 'projects#removed', as: :removed
  get '/explore/help-wanted', to: 'issues#help_wanted', as: :help_wanted
  get '/explore/first-pull-request', to: 'issues#first_pull_request', as: :first_pull_request
  get '/explore/issues', to: 'issues#index', as: :all_issues
  get '/unlicensed-libraries', to: redirect("/explore/unlicensed-libraries")
  get 'unmaintained-libraries', to: redirect("/explore/unmaintained-libraries")
  get 'deprecated-libraries', to: redirect("/explore/deprecated-libraries")
  get 'removed-libraries', to: redirect("/explore/removed-libraries")
  get '/help-wanted', to: redirect("/explore/help-wanted")
  get '/first-pull-request', to: redirect("/explore/first-pull-request")
  

  get '/platforms', to: 'platforms#index', as: :platforms

  scope constraints: {host_type: /(github|gitlab|bitbucket)/i}, defaults: { host_type: 'github' } do
    get '/:host_type/issues', to: 'issues#index', as: :issues
    get '/:host_type/issues/your-dependencies', to: 'issues#your_dependencies', as: :your_dependencies_issues

    post '/hooks/:host_type', to: 'hooks#github'

    get '/:host_type/languages', to: 'repositories#languages', as: :github_languages
    get '/:host_type/search', to: 'repositories#search', as: :github_search
    get '/:host_type/trending', to: 'repositories#hacker_news', as: :trending
    get '/:host_type/new', to: 'repositories#new', as: :new_repos
    get '/:host_type/organisations', to: 'repository_organisations#index', as: :repository_organisations
    get '/:host_type/timeline', to: 'repositories#timeline', as: :github_timeline
    get '/:host_type/:login/issues', to: 'repository_users#issues'
    get '/:host_type/:login/dependencies', to: 'repository_users#dependencies', as: :user_dependencies
    get '/:host_type/:login/dependency-issues', to: 'repository_users#dependency_issues'
    get '/:host_type/:login/repositories', to: 'repository_users#repositories', as: :user_repositories
    get '/:host_type/:login/contributions', to: 'repository_users#contributions', as: :user_contributions
    get '/:host_type/:login/projects', to: 'repository_users#projects', as: :user_projects
    get '/:host_type/:login/contributors', to: 'repository_users#contributors', as: :user_contributors
    get '/:host_type/:login', to: 'repository_users#show', as: :user

    get '/:host_type/:owner/:name', to: 'repositories#show', as: :repository, :defaults => { :format => 'html' }, constraints: { :name => /[\w\.\-\%]+/ }
    get '/:host_type/:owner/:name/contributors', to: 'repositories#contributors', as: :repository_contributors, format: false, constraints: { :name => /[^\/]+/ }
    post '/:host_type/:owner/:name/sync', to: 'repositories#sync', as: :sync_repository, format: false, constraints: { :name => /[^\/]+/ }
    get '/:host_type/:owner/:name/sourcerank', to: 'repositories#sourcerank', as: :repository_sourcerank, format: false, constraints: { :name => /[^\/]+/ }
    get '/:host_type/:owner/:name/forks', to: 'repositories#forks', as: :repository_forks, format: false, constraints: { :name => /[^\/]+/ }
    get '/:host_type/:owner/:name/tags', to: 'repositories#tags', as: :repository_tags, format: false, constraints: { :name => /[^\/]+/ }
    get '/:host_type/:owner/:name/dependency-issues', to: 'repositories#dependency_issues', format: false, constraints: { :name => /[^\/]+/ }
    get '/:host_type/:owner/:name/dependencies', to: 'repositories#dependencies', format: false, constraints: { :name => /[^\/]+/ }, as: :repository_dependencies
    get '/:host_type/:owner/:name/tree', to: 'repository_tree#show', as: :repository_tree, format: false, constraints: { :name => /[^\/]+/ }

    get '/:host_type/:owner/:name/web_hooks', to: 'web_hooks#index', as: :repository_web_hooks, format: false, constraints: { :name => /[^\/]+/ }
    get '/:host_type/:owner/:name/web_hooks/new', to: 'web_hooks#new', as: :new_repository_web_hook, format: false, constraints: { :name => /[^\/]+/ }
    delete '/:host_type/:owner/:name/web_hooks/:id', to: 'web_hooks#destroy', as: :repository_web_hook, format: false, constraints: { :name => /[^\/]+/ }
    patch '/:host_type/:owner/:name/web_hooks/:id', to: 'web_hooks#update', format: false, constraints: { :name => /[^\/]+/ }
    get '/:host_type/:owner/:name/web_hooks/:id/edit', to: 'web_hooks#edit', as: :edit_repository_web_hook, format: false, constraints: { :name => /[^\/]+/ }
    post '/:host_type/:owner/:name/web_hooks/:id/test', to: 'web_hooks#test', as: :test_repository_web_hook, format: false, constraints: { :name => /[^\/]+/ }

app/controllers/api/platforms_controller.rb
class Api::PlatformsController < Api::ApplicationController
  def index
    render json: Platform.all
  end
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  def index
    @platforms = Project.popular_platforms
  end

  def show
    find_platform
    scope = Project.platform(@platform_name).maintained
    @created = scope.few_versions.order('projects.created_at DESC').limit(5).includes(:repository)
    @updated = scope.many_versions.order('projects.latest_release_published_at DESC').limit(5).includes(:repository)
    @watched = scope.most_watched.limit(5).includes(:repository)
    @dependend = scope.most_dependents.limit(5).includes(:repository)
    @popular = scope.order('projects.rank DESC NULLS LAST').limit(5).includes(:repository)
    @trending = scope.includes(:repository).recently_created.hacker_news.limit(5)
    @dependent_repos = scope.most_dependent_repos.limit(5).includes(:repository)

    @color = @platform.color

    facets = Project.facets(filters: {platform: @platform_name}, :facet_limit => 10)

    @languages = facets[:languages].language.buckets
    @licenses = facets[:licenses].normalized_licenses.buckets.reject{ |t| t['key'].downcase == 'other' }
    @keywords = facets[:keywords].keywords_array.buckets
  end
end

app/views/platforms/_list_platform.html.erb
<p class='list'>
  <strong><%= link_to platform_name(platform['key']), search_path(platforms: platform['key'], languages: @language, licenses: @license.try(:id), keywords: @keyword) %></strong>
  <small><%= pluralize number_to_human(platform['doc_count']), 'project' %></small>
</p>

app/views/platforms/_platform.html.erb
<div class='platform col-xs-6 col-sm-4 col-md-4'>
  <h4>
    <div class="pictogram pictogram-<%= platform['key'].downcase %>"></div>
    <div class="blurb">
      <%= link_to platform_name(platform['key']), platform_path(platform['key'].downcase) %>
      <small><%= number_to_human platform['doc_count'] %> Projects</small>
    </div>
  </h4>
</div>

app/views/platforms/index.html.erb
<% title "Platforms - Libraries.io" %>
<% description "All the open source platforms that projects have been published to" %>
<h1>
  <%= fa_icon 'archive' %>
  Package Managers
</h1><hr>
<div class='row'>
  <div class="col-md-8">
    <div class="row">
      <%= render partial: 'platform', collection: @platforms %>
    </div>
  </div>
  <div class="col-md-4">
    <%= render 'adsense/sidebar' %>
  </div>
</div>

app/views/platforms/show.html.erb
<% title "#{platform_name(@platform_name)} - Libraries.io" %>
<% description "A detailed listing of the most popular, recently updated and most watched #{platform_name(@platform_name)} projects online" %>
<% content_for :atom, auto_discovery_link_tag(:atom, search_url(platforms: @platform_name, sort: 'latest_release_published_at', order: 'desc', format: :atom), title: "Updated #{platform_name(@platform_name)} Projects") %>
<% content_for :atom, auto_discovery_link_tag(:atom, search_url(platforms: @platform_name, sort: 'created_at', order: 'desc', format: :atom), title: "New #{platform_name(@platform_name)} Projects") %>

<% cache([@platform_name, 'platforms:show', 'v1'], :expires_in => 1.hour) do %>
<div class='row'>
  <div class='col-sm-6'>
    <h1>
      <div class="pictogram pictogram-lg pictogram-<%= @platform_name.downcase %>"></div>
      <%= platform_name(@platform_name) %>
    </h1>
  </div>
  <div class="col-sm-6">
    <br>
    <p>
      Website: <%= link_to @platform::URL, @platform::URL %>
    </p>
    <p>
      Total Packages: <%= number_with_delimiter Project.platform(@platform_name).not_removed.count %>
    </p>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-8">
    <div class="row">
      <% if @trending.any? %>
        <div class='col-sm-6 platform-column'>
          <h4>
            Trending <%= platform_name(@platform_name) %> Projects
            <small class='more'>
              <%= link_to 'See more &raquo;'.html_safe, trending_projects_path(platforms: @platform_name) %>
            </small>
          </h4>
          <%= render @trending, cache: true %>
        </div>
      <% end %>

      <% if @popular.any? %>
        <div class='col-sm-6 platform-column'>
          <h4>
            Popular <%= platform_name(@platform_name) %> Projects
            <small class='more'>
              <%= link_to 'See more &raquo;'.html_safe, search_path(platforms: @platform_name, sort: 'rank', order: 'desc') %>
            </small>
          </h4>
          <%= render @popular, cache: true %>
        </div>
      <% end %>

      <% if @dependent_repos.any? %>
        <div class='col-sm-6 platform-column'>
          <h4>Most Used <%= platform_name(@platform_name) %> Projects</h4>
          <%= render @dependent_repos, cache: true %>
        </div>
      <% end %>

      <% if @dependend.any? %>
        <div class='col-sm-6 platform-column'>
          <h4>Most Depended upon <%= platform_name(@platform_name) %> Projects</h4>
          <%= render @dependend, cache: true %>
        </div>
      <% end %>

      <% if @updated.any? %>
      <div class='col-sm-6 platform-column'>
        <h4>
          <%= link_to search_url(platforms: @platform_name, sort: 'latest_release_published_at', order: 'desc', format: :atom), class: 'rss' do %>
            <%= fa_icon "rss-square" %>
          <% end %>
          Updated <%= platform_name(@platform_name) %> Projects
          <small class='more'>
            <%= link_to 'See more &raquo;'.html_safe, search_path(platforms: @platform_name, sort: 'latest_release_published_at', order: 'desc') %>
          </small>
        </h4>
        <%= render @updated, cache: true %>
      </div>
      <% end %>
      <% if @created.any? %>
        <div class='col-sm-6 platform-column'>
          <h4>
            <%= link_to search_url(platforms: @platform_name, sort: 'created_at', order: 'desc', format: :atom), class: 'rss' do %>
              <%= fa_icon "rss-square" %>
            <% end %>
            New <%= platform_name(@platform_name) %> Projects
            <small class='more'>
              <%= link_to 'See more &raquo;'.html_safe, search_path(platforms: @platform_name, sort: 'created_at', order: 'desc') %>
            </small>
          </h4>
          <%= render @created, cache: true %>
        </div>
      <% end %>

      <% if @watched.any? %>
          <div class='col-sm-6 platform-column'>
            <h4>Most Watched <%= platform_name(@platform_name) %> Projects</h4>
            <%= render @watched, cache: true %>
          </div>
          <div class="col-sm-6">
            <%= render 'adsense/sidebar' %>
          </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-4">
    <%= render 'adsense/sidebar' %>
    <div class='row'>
      <% if @languages.many? %>
        <div class='col-md-12 col-sm-4'>
          <h4>
            <%= fa_icon 'code' %>
            Top <%= platform_name(@platform_name) %> Languages
          </h4>
          <%= render partial: 'languages/list_language', collection: @languages, as: :language %>
        </div>
      <% end %>
      <% if @licenses.many? %>
        <div class='col-md-12 col-sm-4'>
          <h4>
            <%= fa_icon 'gavel' %>
            Top <%= platform_name(@platform_name) %> Licenses
          </h4>
          <%= render partial: 'licenses/list_license', collection: @licenses, as: :license %>
        </div>
      <% end %>
      <% if @keywords.many? %>
        <div class='col-md-12 col-sm-4'>
          <h4>
            <%= fa_icon 'tags' %>
            Top <%= platform_name(@platform_name) %> Keywords
          </h4>
          <%= render partial: 'keywords/list_keyword', collection: @keywords, as: :keyword %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>